name: Deploy Dashboard with Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # 매일 한 시간마다 자동으로 실행되도록 설정
    # (예: 매시 정각 00분)
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment

    permissions:
      contents: write # Grant permission to write files to the repository (for gh-pages branch)

    steps:
      - name: Checkout repository # Checkout the repository code (from main branch)
        uses: actions/checkout@v4

      # --- Python environment setup and data fetching steps ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Use Python 3.10

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas # Install gspread and pandas libraries

      - name: Create data directory
        run: mkdir -p data # Create 'data/' directory to save the JSON file

      - name: Fetch and Process Data from Google Sheet
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: python scripts/fetch_chart_data.py # Execute the Python script to fetch data
      # --- End Python related steps ---

      - name: Deploy to GitHub Pages # Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use peaceiris/actions-gh-pages action v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub-provided token for deployment
          publish_dir: ./ # Publish files from the root directory of the repository
          publish_branch: gh-pages # Publish the deployed files to the 'gh-pages' branch
